
import {Edu_AU_VIC_WA_NT_Hand} from "next/font/google"
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Header from "@/components/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   weight:'400'
// });
const myFont = Edu_AU_VIC_WA_NT_Hand({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:'400'
});

// console.log(myFont);


export const metadata = {
  title: "My Front App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className}`}>
        <Header />
        <div className="container mb-2">{children}</div>
      </body>
    </html>
  );
}
// localhost:3000/
// localhost:3000/about
// localhost:3000/contactus
// localhost:3000/products
